name: 'Validate Submission' 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: 'https://dev.azure.com/test-memhub/test-hub'
        azure-pipeline-name: 'microsoft.configmgr-hub-selfhost'
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
